// Canonical forms are accent-free because review text is normalized before matching.
// Longer phrases come first so flaggedWords reports the most useful context.
export const BAD_WORDS = [
  'mon nhu cut',
  'an nhu cut',
  'do nhu cut',
  'te nhu cut',
  'nau nhu cut',
  'ngu nhu cho',
  'nhu con c',
  'nhu cut',
  'do nhu db',
  'nhu db',
  'nhu cc',
  'oc cho',
  'do ngu',
  'do cho',
  'cut di',
  'bien di',
  'rac ruoi',
  'phe vat',
  'vo dung',
  'ham l',
  'mat day',
  'bo lao',
  'xam l',
  'do vai',
  'do vl',
  'te vl',
  'me may',
  'con c',
  'suc vat',
  'nhu lon',
  'con cac',
  'cut',
  'shit',
  'db',
  'cc',
  'dit',
  'deo',
  'dell',
  'vcl',
  'vl',
  'vai l',
  'clm',
  'dcm',
  'dmm',
  'dm',
  'djt',
  'ngu',
  'rac',
  'xam',
  'fuck',
  'fucking',
  'bitch',
  'bastard',
  'idiot',
  'retard',
] as const;

// These words become common Vietnamese words after removing accents:
// "cặc" -> "cac" (các), "lồn" -> "lon" (lớn), "đụ" -> "du" (đủ),
// and "chó" -> "cho" (cho). Match their accented spelling separately.
export const ACCENT_SENSITIVE_BAD_WORDS = [
  'cặc',
  'lồn',
  'đụ',
  'chó',
  'hãm',
] as const;

export const INAPPROPRIATE_REVIEW_TEXT = 'Nội dung không phù hợp';
export const FLAGGED_REVIEW_REASON =
  'Nội dung chứa từ ngữ không phù hợp';
