import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { MealPlan } from './entities/meal-plan.entity';
import { MealPlanItem } from './entities/meal-plan-item.entity';
import { Recipe } from '../recipes/entities/recipe.entity';
import { RecommendationService } from '../recommendation/recommendation.service';
import { CalorieService } from '../recommendation/calorie.service';
import { User } from '../auth/entities/user.entity';
import { Inventory } from '../inventory/entities/inventory.entity';
import { ShoppingList } from '../shopping-list/entities/shopping-list.entity';

@Injectable()
export class MealPlanService {
    // Day labels in Vietnamese
    private readonly DAY_LABELS = [
        '', 'Thứ Hai', 'Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu', 'Thứ Bảy', 'Chủ Nhật',
    ];

    private readonly MEAL_TYPES = ['breakfast', 'lunch', 'dinner'];

    constructor(
        @InjectRepository(MealPlan) private planRepo: Repository<MealPlan>,
        @InjectRepository(MealPlanItem) private itemRepo: Repository<MealPlanItem>,
        @InjectRepository(Recipe) private recipeRepo: Repository<Recipe>,
        @InjectRepository(User) private userRepo: Repository<User>,
        @InjectRepository(Inventory) private inventoryRepo: Repository<Inventory>,
        private recommendationService: RecommendationService,
        private calorieService: CalorieService,
    ) { }

    /**
     * Get meal plan for a specific week
     */
    async findByWeek(userId: string, weekStart?: string) {
        const startDate = weekStart
            ? this.parseDateInput(weekStart)
            : this.getMonday(new Date());

        const plan = await this.planRepo.findOne({
            where: { userId, weekStart: startDate },
            relations: ['items', 'items.recipe'],
        });

        if (!plan) return null;

        // Build response with day labels and nutrition data
        const items = plan.items.map((item) => ({
            id: item.id,
            dayOfWeek: this.getDayOfWeekIndex(item.mealDate),
            dayLabel: this.DAY_LABELS[this.getDayOfWeekIndex(item.mealDate)],
            mealDate: item.mealDate instanceof Date ? this.formatDateInput(item.mealDate) : item.mealDate,
            mealType: item.mealType,
            recipe: item.recipe
                ? {
                    id: item.recipe.id,
                    name: item.recipe.name,
                    imageUrl: item.recipe.imageUrl,
                    calories: item.recipe.calories,
                    cookingTime: item.recipe.cookingTime,
                }
                : null,
            calories: item.calories,
            isLocked: item.isLocked,
            isConsumed: item.isConsumed,
        }));

        // Calculate daily nutrition
        const nutrition = this.calculateNutrition(plan.items);

        return {
            id: plan.id,
            weekStart: plan.weekStart,
            weekEnd: plan.weekEnd,
            isAutoGenerated: plan.isAutoGenerated,
            status: plan.status,
            totalCalories: plan.totalCalories,
            dailyAvgCalories: Math.round((plan.totalCalories || 0) / 7),
            items,
            nutrition,
        };
    }

    /**
     * Get meal plan by specific ID
     */
    async findById(userId: string, id: string) {
        const plan = await this.planRepo.findOne({
            where: { id, userId },
            relations: ['items', 'items.recipe'],
        });

        if (!plan) return null;

        const items = plan.items.map((item) => ({
            id: item.id,
            dayOfWeek: this.getDayOfWeekIndex(item.mealDate),
            dayLabel: this.DAY_LABELS[this.getDayOfWeekIndex(item.mealDate)],
            mealDate: item.mealDate instanceof Date ? this.formatDateInput(item.mealDate) : item.mealDate,
            mealType: item.mealType,
            recipe: item.recipe
                ? {
                    id: item.recipe.id,
                    name: item.recipe.name,
                    imageUrl: item.recipe.imageUrl,
                    calories: item.recipe.calories,
                    cookingTime: item.recipe.cookingTime,
                }
                : null,
            calories: item.calories,
            isLocked: item.isLocked,
            isConsumed: item.isConsumed,
        }));

        const nutrition = this.calculateNutrition(plan.items);

        return {
            id: plan.id,
            weekStart: plan.weekStart,
            weekEnd: plan.weekEnd,
            isAutoGenerated: plan.isAutoGenerated,
            status: plan.status,
            totalCalories: plan.totalCalories,
            dailyAvgCalories: Math.round((plan.totalCalories || 0) / 7),
            items,
            nutrition,
        };
    }


    /**
     * AI-generate a weekly meal plan
     * Uses greedy sequential selection with diversity enforcement
     */
    async generate(
        userId: string,
        dto: {
            weekStart: string;
            useAntiWaste?: boolean;
            lockedItems?: { dayOfWeek?: number; mealDate?: string; mealType: string; recipeId: string }[];
            emptyPlan?: boolean;
            overwrite?: boolean;
        },
    ) {
        const weekStart = this.parseDateInput(dto.weekStart || this.formatDateInput(this.getMonday(new Date())));
        this.ensureWeekHasCreatableDate(weekStart);
        const weekEnd = new Date(weekStart);
        weekEnd.setDate(weekEnd.getDate() + 6);
        const weekStartValue = this.formatDateInput(weekStart);

        // Delete existing plan items for this week (if any) and reuse the plan record to avoid foreign key violations with shopping lists
        const existing = await this.planRepo.findOne({
            where: { userId, weekStart },
        });
        
        let plan: MealPlan;
        if (existing) {
            if (dto.overwrite === true) {
                await this.itemRepo.delete({ mealPlanId: existing.id, isLocked: false });
            }
            existing.isAutoGenerated = !dto.emptyPlan;
            existing.status = 'active';
            existing.totalCalories = 0;
            plan = await this.planRepo.save(existing);
        } else {
            // Create new plan
            plan = this.planRepo.create({
                userId,
                weekStart,
                weekEnd,
                isAutoGenerated: !dto.emptyPlan,
                status: 'active',
            });
            await this.planRepo.save(plan);
        }

        if (dto.emptyPlan) {
            if (existing) {
                await this.itemRepo.delete({ mealPlanId: existing.id });
            }
            return this.findByWeek(userId, weekStartValue);
        }

        // Fetch user context for servings
        const user = await this.userRepo.findOne({
            where: { id: userId },
            relations: ['preferences'],
        });
        const servings = user?.preferences?.servings || 4;

        // Track used recipes for diversity
        const usedRecipeIds = new Set<string>();
        const items: MealPlanItem[] = [];
        let totalCalories = 0;

        // Fetch existing items for weekly plan (if any)
        const existingItems = existing 
            ? await this.itemRepo.find({ where: { mealPlanId: existing.id }, relations: ['recipe'] })
            : [];

        // Locked items map for quick lookup. Since a slot can have multiple locked items:
        const lockedMap = new Map<string, string[]>();
        if (dto.lockedItems) {
            dto.lockedItems.forEach((li) => {
                let targetDateStr = '';
                if (li.mealDate) {
                    targetDateStr = li.mealDate;
                } else if (li.dayOfWeek) {
                    const d = new Date(weekStart);
                    d.setDate(d.getDate() + (li.dayOfWeek - 1));
                    targetDateStr = this.formatDateInput(d);
                }
                if (targetDateStr) {
                    const key = `${targetDateStr}-${li.mealType}`;
                    const list = lockedMap.get(key) || [];
                    list.push(li.recipeId);
                    lockedMap.set(key, list);
                }
            });
        }

        // Generate meals: iterate day by day, meal by meal
        for (let i = 0; i < 7; i++) {
            const currentDate = new Date(weekStart);
            currentDate.setDate(currentDate.getDate() + i);
            const dateStr = this.formatDateInput(currentDate);

            if (this.isDateInPast(currentDate)) continue;

            for (const mealType of this.MEAL_TYPES) {
                const key = `${dateStr}-${mealType}`;

                // Get existing items for this slot in DB
                const slotExistingItems = existingItems.filter(
                    item => this.formatDateInput(new Date(item.mealDate)) === dateStr && item.mealType === mealType
                );
                const recipesAlreadyInSlot = slotExistingItems.filter(item => item.recipeId !== null);

                // If overwrite is false, and slot has recipes, keep them intact
                if (dto.overwrite !== true && recipesAlreadyInSlot.length > 0) {
                    for (const item of recipesAlreadyInSlot) {
                        items.push(item);
                        if (item.recipeId) {
                            usedRecipeIds.add(item.recipeId);
                            totalCalories += item.calories || 0;
                        }
                    }
                    continue;
                }

                const lockedRecipeIds = lockedMap.get(key) || [];
                const slotLockedItems = slotExistingItems.filter(item => item.isLocked);
                
                // Add locked items to this slot
                for (const item of slotLockedItems) {
                    items.push(item);
                    if (item.recipeId) {
                        usedRecipeIds.add(item.recipeId);
                        totalCalories += item.calories || 0;
                    }
                }
                
                // Fetch user locked recipes passed in dto.lockedItems
                for (const recipeId of lockedRecipeIds) {
                    // Avoid duplicating locked items already pushed
                    if (slotLockedItems.some(li => li.recipeId === recipeId)) continue;
                    
                    const recipe = await this.recipeRepo.findOne({ where: { id: recipeId } });
                    if (recipe) {
                        const item = this.itemRepo.create({
                            mealPlanId: plan.id,
                            recipeId: recipe.id,
                            mealDate: currentDate,
                            mealType,
                            calories: recipe.calories,
                            isLocked: true,
                        });
                        items.push(item);
                        usedRecipeIds.add(recipe.id);
                        totalCalories += recipe.calories;
                    }
                }

                const targetCount = this.getTargetDishesCount(servings, mealType);
                const currentCount = slotLockedItems.length + lockedRecipeIds.filter(id => !slotLockedItems.some(li => li.recipeId === id)).length;
                if (currentCount >= targetCount) {
                    continue;
                }

                const neededCount = targetCount - currentCount;

                // Use AI to get recommendations for this slot
                const recs = await this.recommendationService.getRecommendations(
                    userId,
                    mealType,
                    15, // request more options to ensure we have main, rau, canh
                    dto.useAntiWaste !== false,
                );

                // Select recipes based on classification
                const selectedRecipes = this.selectRecipesForSlot(recs.recommendations, neededCount, usedRecipeIds);

                for (const recipe of selectedRecipes) {
                    const item = this.itemRepo.create({
                        mealPlanId: plan.id,
                        recipeId: recipe.id,
                        mealDate: currentDate,
                        mealType,
                        calories: recipe.calories,
                        isLocked: false,
                    });
                    items.push(item);
                    totalCalories += recipe.calories;
                }
            }
        }

        // Save only newly created items (where id is undefined/null)
        const newItems = items.filter(item => !item.id);
        if (newItems.length > 0) {
            await this.itemRepo.save(newItems);
        }

        // Update total calories
        plan.totalCalories = totalCalories;
        await this.planRepo.save(plan);

        return this.findByWeek(userId, weekStartValue);
    }

    async swapRecipe(userId: string, planId: string, itemId: string, recipeId: string) {
        const item = await this.itemRepo.findOne({
            where: { id: itemId, mealPlanId: planId },
        });
        if (!item) throw new NotFoundException('Meal plan item not found');

        const recipe = await this.recipeRepo.findOne({ where: { id: recipeId } });
        if (!recipe) throw new NotFoundException('Recipe not found');

        item.recipeId = recipe.id;
        item.calories = recipe.calories;
        await this.itemRepo.save(item);

        // Recalculate total calories
        await this.recalculateTotalCalories(planId);

        return {
            id: item.id,
            dayOfWeek: this.getDayOfWeekIndex(item.mealDate),
            mealDate: item.mealDate instanceof Date ? this.formatDateInput(item.mealDate) : item.mealDate,
            mealType: item.mealType,
            recipe: {
                id: recipe.id,
                name: recipe.name,
                calories: recipe.calories,
            },
            calories: recipe.calories,
            isLocked: item.isLocked,
            isConsumed: item.isConsumed,
        };
    }

    /**
     * Add or update a specific meal slot in a plan by day and mealType
     */
    async setMealSlot(userId: string, mealDate: string, mealType: string, recipeId: string, overwrite = false) {
        const targetDate = this.parseDateInput(mealDate);
        this.ensureDateIsCreatable(targetDate);
        const startDate = this.getMonday(targetDate);

        // 1. Get or create meal plan for this week
        let plan = await this.planRepo.findOne({
            where: { userId, weekStart: startDate }
        });
        if (!plan) {
            const endDate = new Date(startDate);
            endDate.setDate(endDate.getDate() + 6);

            plan = this.planRepo.create({
                userId,
                weekStart: startDate,
                weekEnd: endDate,
                isAutoGenerated: false,
                status: 'active',
                totalCalories: 0,
            });
            await this.planRepo.save(plan);
        }

        // 2. Fetch the recipe to get calories
        const recipe = await this.recipeRepo.findOne({ where: { id: recipeId } });
        if (!recipe) throw new NotFoundException('Recipe not found');

        // Check if there are already items in this slot (locked or non-locked)
        const existingItems = await this.itemRepo.find({
            where: { mealPlanId: plan.id, mealDate: targetDate, mealType }
        });

        const hasRecipe = existingItems.some(item => item.recipeId !== null);
        if (hasRecipe && !overwrite) {
            // Check if exact recipe matches to return early
            const isExactRecipe = existingItems.some(item => item.recipeId === recipe.id);
            if (isExactRecipe) {
                return this.findByWeek(userId, this.formatDateInput(startDate));
            }
            // Otherwise, skip update (do not overwrite)
            return this.findByWeek(userId, this.formatDateInput(startDate));
        }

        // If overwrite is true, delete existing items in this slot first
        if (overwrite && existingItems.length > 0) {
            await this.itemRepo.remove(existingItems);
        }

        // Create the item for this slot
        const item = this.itemRepo.create({
            mealPlanId: plan.id,
            mealDate: targetDate,
            mealType,
            recipeId: recipe.id,
            calories: recipe.calories,
            isLocked: true, // Keep locked so AI generation won't overwrite it
        });
        await this.itemRepo.save(item);

        // Recalculate total calories
        await this.recalculateTotalCalories(plan.id);

        return this.findByWeek(userId, this.formatDateInput(startDate));
    }

    /**
     * Generate or update recipes specifically for a set of days (leaving other days unchanged)
     */
    async generateForDays(
        userId: string,
        dto: {
            weekStart?: string;
            days?: number[];
            mealDates?: string[];
            useAntiWaste?: boolean;
            mealType?: string;
            overwrite?: boolean;
        }
    ) {
        let mealDates = dto.mealDates;
        if ((!mealDates || mealDates.length === 0) && dto.weekStart && dto.days) {
            const start = this.parseDateInput(dto.weekStart);
            mealDates = dto.days.map((day) => {
                const d = new Date(start);
                d.setDate(d.getDate() + (day - 1));
                return this.formatDateInput(d);
            });
        }

        if (!mealDates || mealDates.length === 0) {
            throw new BadRequestException('Vui lòng chọn ít nhất một ngày để tạo thực đơn.');
        }

        const parsedDates = mealDates.map(d => this.parseDateInput(d));
        parsedDates.forEach(date => this.ensureDateIsCreatable(date));
        
        // Find weekStart from the first date
        const weekStart = this.getMonday(parsedDates[0]);
        
        // 1. Get or create the meal plan for this week
        let plan = await this.planRepo.findOne({
            where: { userId, weekStart }
        });

        if (!plan) {
            const startDate = new Date(weekStart);
            const endDate = new Date(startDate);
            endDate.setDate(endDate.getDate() + 6);

            plan = this.planRepo.create({
                userId,
                weekStart: startDate,
                weekEnd: endDate,
                isAutoGenerated: true,
                status: 'active',
                totalCalories: 0,
            });
            await this.planRepo.save(plan);
        } else if (dto.overwrite === true) {
            // Delete existing non-locked items for the specified dates and mealType (if provided) so we can regenerate them
            const deleteCriteria: any = { 
                mealPlanId: plan.id,
                mealDate: In(parsedDates.map(d => this.formatDateInput(d))),
                isLocked: false 
            };
            if (dto.mealType) {
                deleteCriteria.mealType = dto.mealType;
            }
            await this.itemRepo.delete(deleteCriteria);
        }

        // Fetch user context for servings
        const user = await this.userRepo.findOne({
            where: { id: userId },
            relations: ['preferences'],
        });
        const servings = user?.preferences?.servings || 4;

        // 2. Track used recipe IDs in this plan to keep it diverse
        const existingItems = await this.itemRepo.find({
            where: { mealPlanId: plan.id },
            relations: ['recipe'],
        });
        const usedRecipeIds = new Set<string>(
            existingItems.filter(item => item.recipe).map(item => item.recipe.id)
        );

        // 3. Generate meals for each specified day and meal type
        const mealTypesToGenerate = dto.mealType ? [dto.mealType] : this.MEAL_TYPES;
        for (const date of parsedDates) {
            const dateStr = this.formatDateInput(date);
            for (const mealType of mealTypesToGenerate) {
                // Get existing items for this slot
                const slotExistingItems = existingItems.filter(
                    item => this.formatDateInput(new Date(item.mealDate)) === dateStr && item.mealType === mealType
                );
                const recipesAlreadyInSlot = slotExistingItems.filter(item => item.recipeId !== null);

                // Under "Suggest missing (overwrite = false)", if there is any recipe in this slot, skip it
                if (dto.overwrite !== true && recipesAlreadyInSlot.length > 0) {
                    continue;
                }

                // Get locked items for this slot
                const slotLockedItems = slotExistingItems.filter(item => item.isLocked);
                const targetCount = this.getTargetDishesCount(servings, mealType);
                if (slotLockedItems.length >= targetCount) {
                    continue;
                }

                const neededCount = targetCount - slotLockedItems.length;

                // Use AI to get recommendations for this slot
                const recs = await this.recommendationService.getRecommendations(
                    userId,
                    mealType,
                    15, // request more options to ensure we have main, rau, canh
                    dto.useAntiWaste !== false,
                );

                // Select recipes based on classification
                const selectedRecipes = this.selectRecipesForSlot(recs.recommendations, neededCount, usedRecipeIds);

                for (const recipe of selectedRecipes) {
                    const item = this.itemRepo.create({
                        mealPlanId: plan.id,
                        recipeId: recipe.id,
                        mealDate: date,
                        mealType,
                        calories: recipe.calories,
                        isLocked: false,
                    });
                    await this.itemRepo.save(item);
                }
            }
        }

        // 4. Recalculate daily average calories and total calories
        await this.recalculateTotalCalories(plan.id);

        return this.findByWeek(userId, this.formatDateInput(weekStart));
    }

    /**
     * Lock/unlock a meal slot
     */
    async toggleLock(userId: string, planId: string, itemId: string, isLocked: boolean) {
        const plan = await this.planRepo.findOne({ where: { id: planId, userId } });
        if (!plan) throw new NotFoundException('Meal plan not found');

        const item = await this.itemRepo.findOne({
            where: { id: itemId, mealPlanId: planId },
        });
        if (!item) throw new NotFoundException('Meal plan item not found');

        item.isLocked = isLocked;
        await this.itemRepo.save(item);
        return { id: item.id, isLocked: item.isLocked };
    }

    async removeItem(userId: string, planId: string, itemId: string) {
        const plan = await this.planRepo.findOne({ where: { id: planId, userId } });
        if (!plan) throw new NotFoundException('Meal plan not found');

        const item = await this.itemRepo.findOne({ where: { id: itemId, mealPlanId: planId } });
        if (!item) throw new NotFoundException('Meal plan item not found');

        await this.itemRepo.remove(item);

        // Recalculate total calories
        await this.recalculateTotalCalories(planId);

        return { message: 'Meal plan item removed' };
    }

    /**
     * Delete a meal plan
     */
    async remove(userId: string, planId: string) {
        const plan = await this.planRepo.findOne({ where: { id: planId, userId } });
        if (!plan) throw new NotFoundException('Meal plan not found');

        // Disassociate any shopping lists referencing this plan to avoid foreign key violation
        await this.planRepo.manager.update(ShoppingList, { mealPlanId: planId }, { mealPlanId: null });

        // Delete related items first to ensure foreign key constraint satisfaction in case ON DELETE CASCADE is not synced
        await this.itemRepo.delete({ mealPlanId: planId });

        await this.planRepo.remove(plan);
        return { message: 'Meal plan deleted' };
    }

    /**
     * Get nutrition breakdown for charts (Chart.js data)
     */
    async getNutrition(userId: string, planId: string) {
        const plan = await this.planRepo.findOne({
            where: { id: planId, userId },
            relations: ['items', 'items.recipe'],
        });
        if (!plan) throw new NotFoundException('Meal plan not found');

        const user = await this.userRepo.findOne({ where: { id: userId } });
        const daily = this.calculateNutrition(plan.items);

        // Calculate weekly averages
        const weeklyAvg = {
            calories: Math.round(daily.reduce((sum, d) => sum + d.calories, 0) / 7),
            protein: Math.round(daily.reduce((sum, d) => sum + d.protein, 0) / 7 * 10) / 10,
            carbs: Math.round(daily.reduce((sum, d) => sum + d.carbs, 0) / 7 * 10) / 10,
            fat: Math.round(daily.reduce((sum, d) => sum + d.fat, 0) / 7 * 10) / 10,
        };

        // Macro distribution percentages
        const totalMacroCalories =
            weeklyAvg.protein * 4 + weeklyAvg.carbs * 4 + weeklyAvg.fat * 9;
        const macroDistribution = {
            proteinPercent: Math.round((weeklyAvg.protein * 4 / totalMacroCalories) * 100 * 10) / 10,
            carbsPercent: Math.round((weeklyAvg.carbs * 4 / totalMacroCalories) * 100 * 10) / 10,
            fatPercent: Math.round((weeklyAvg.fat * 9 / totalMacroCalories) * 100 * 10) / 10,
        };

        return {
            calorieTarget: user.dailyCalorieTarget,
            daily,
            weeklyAvg,
            macroDistribution,
        };
    }

    private calculateNutrition(items: MealPlanItem[]) {
        const dailyMap = new Map<number, { calories: number; protein: number; carbs: number; fat: number }>();

        for (let d = 1; d <= 7; d++) {
            dailyMap.set(d, { calories: 0, protein: 0, carbs: 0, fat: 0 });
        }

        for (const item of items) {
            if (item.recipe) {
                const dayOfWeek = this.getDayOfWeekIndex(item.mealDate);
                const day = dailyMap.get(dayOfWeek);
                if (day) {
                    day.calories += item.recipe.calories || 0;
                    day.protein += Number(item.recipe.protein) || 0;
                    day.carbs += Number(item.recipe.carbs) || 0;
                    day.fat += Number(item.recipe.fat) || 0;
                }
            }
        }

        return Array.from(dailyMap.entries()).map(([day, data]) => ({
            day,
            label: this.DAY_LABELS[day],
            ...data,
        }));
    }

    private async recalculateTotalCalories(planId: string) {
        const items = await this.itemRepo.find({ where: { mealPlanId: planId } });
        const total = items.reduce((sum, item) => sum + (item.calories || 0), 0);
        await this.planRepo.update(planId, { totalCalories: total });
    }

    private getMonday(d: Date): Date {
        const target = this.dateOnly(d);
        const day = target.getDay();
        const diff = target.getDate() - day + (day === 0 ? -6 : 1);
        target.setDate(diff);
        return target;
    }

    private parseDateInput(value: string | Date): Date {
        if (value instanceof Date) return this.dateOnly(value);

        const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(value);
        if (!match) {
            const parsed = new Date(value);
            if (Number.isNaN(parsed.getTime())) {
                throw new BadRequestException('Ngày không hợp lệ. Vui lòng dùng định dạng YYYY-MM-DD.');
            }
            return this.dateOnly(parsed);
        }

        return new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
    }

    private dateOnly(date: Date): Date {
        return new Date(date.getFullYear(), date.getMonth(), date.getDate());
    }

    private formatDateInput(date: Date): string {
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        return `${year}-${month}-${day}`;
    }

    private getDayOfWeekIndex(date: Date | string): number {
        const d = new Date(date);
        const day = d.getDay(); // 0 = Sunday, 1 = Monday, ..., 6 = Saturday
        return day === 0 ? 7 : day;
    }

    private isDateInPast(date: Date): boolean {
        return this.dateOnly(date) < this.dateOnly(new Date());
    }

    private ensureDateIsCreatable(date: Date) {
        if (this.isDateInPast(date)) {
            throw new BadRequestException('Không thể tạo hoặc chỉnh sửa thực đơn cho ngày đã qua.');
        }
    }

    private ensureWeekHasCreatableDate(weekStart: Date) {
        const weekEnd = new Date(weekStart);
        weekEnd.setDate(weekEnd.getDate() + 6);
        if (weekEnd < this.dateOnly(new Date())) {
            throw new BadRequestException('Không thể tạo thực đơn cho tuần đã qua.');
        }
    }

    private getTargetDishesCount(servings: number, mealType: string): number {
        if (mealType === 'breakfast' || mealType === 'snack') {
            return 1;
        }
        if (servings <= 2) {
            return 1;
        }
        if (servings <= 5) {
            return 2;
        }
        return 3;
    }

    private selectRecipesForSlot(
        recommendations: any[],
        targetCount: number,
        usedRecipeIds: Set<string>,
    ): any[] {
        if (!recommendations || recommendations.length === 0) return [];
        if (targetCount <= 1) {
            const found = recommendations.find((r) => !usedRecipeIds.has(r.recipe.id));
            return found ? [found.recipe] : [recommendations[0].recipe];
        }

        const mains: any[] = [];
        const raws: any[] = []; // vegetables
        const soups: any[] = []; // soup

        for (const rec of recommendations) {
            const recipe = rec.recipe;
            const tags = recipe.tags || [];
            if (tags.includes('canh')) {
                soups.push(recipe);
            } else if (tags.includes('rau')) {
                raws.push(recipe);
            } else {
                mains.push(recipe);
            }
        }

        const selected: any[] = [];

        // Select main dish
        const main = mains.find((r) => !usedRecipeIds.has(r.id)) || mains[0];
        if (main) {
            selected.push(main);
            usedRecipeIds.add(main.id);
        }

        if (targetCount === 2) {
            // Need 1 side dish: either rau or canh
            const side = raws.find((r) => !usedRecipeIds.has(r.id)) ||
                         soups.find((r) => !usedRecipeIds.has(r.id)) ||
                         raws[0] || soups[0];
            if (side) {
                selected.push(side);
                usedRecipeIds.add(side.id);
            }
        } else if (targetCount === 3) {
            // Need 1 rau and 1 canh
            const veg = raws.find((r) => !usedRecipeIds.has(r.id)) || raws[0];
            if (veg) {
                selected.push(veg);
                usedRecipeIds.add(veg.id);
            }
            const soup = soups.find((r) => !usedRecipeIds.has(r.id)) || soups[0];
            if (soup) {
                selected.push(soup);
                usedRecipeIds.add(soup.id);
            }
        }

        // Fallback: if not enough dishes, fill with any unused recommendations
        while (selected.length < targetCount && selected.length < recommendations.length) {
            const remaining = recommendations.find((r) => !usedRecipeIds.has(r.recipe.id));
            if (!remaining) {
                const anyRemaining = recommendations.find((r) => !selected.some((s) => s.id === r.recipe.id));
                if (anyRemaining) {
                    selected.push(anyRemaining.recipe);
                } else {
                    break;
                }
            } else {
                selected.push(remaining.recipe);
                usedRecipeIds.add(remaining.recipe.id);
            }
        }

        return selected;
    }

    async toggleConsume(userId: string, planId: string, itemId: string, isConsumed: boolean) {
        const item = await this.itemRepo.findOne({
            where: { id: itemId, mealPlanId: planId },
            relations: ['recipe', 'recipe.recipeIngredients', 'recipe.recipeIngredients.ingredient'],
        });
        if (!item) {
            throw new NotFoundException('Không tìm thấy bữa ăn trong thực đơn');
        }

        if (item.isConsumed === isConsumed) {
            return { message: 'Trạng thái không thay đổi', isConsumed: item.isConsumed };
        }

        const user = await this.userRepo.findOne({
            where: { id: userId },
            relations: ['preferences'],
        });
        if (!user) {
            throw new NotFoundException('Không tìm thấy thông tin người dùng');
        }

        const servings = user.preferences?.servings || 4;
        const recipe = item.recipe;

        item.isConsumed = isConsumed;
        await this.itemRepo.save(item);

        if (recipe && recipe.recipeIngredients && recipe.recipeIngredients.length > 0) {
            const recipeServings = recipe.servings || 4;
            const ratio = servings / recipeServings;

            for (const ri of recipe.recipeIngredients) {
                const amountNeeded = Number(ri.quantity) * ratio;

                const invItem = await this.inventoryRepo.findOne({
                    where: { userId, ingredientId: ri.ingredientId },
                });

                if (isConsumed) {
                    if (invItem) {
                        const newQty = Number(invItem.quantity) - amountNeeded;
                        if (newQty <= 0) {
                            await this.inventoryRepo.remove(invItem);
                        } else {
                            invItem.quantity = Math.round(newQty * 100) / 100;
                            await this.inventoryRepo.save(invItem);
                        }
                    }
                } else {
                    if (invItem) {
                        const newQty = Number(invItem.quantity) + amountNeeded;
                        invItem.quantity = Math.round(newQty * 100) / 100;
                        await this.inventoryRepo.save(invItem);
                    } else {
                        const newInv = this.inventoryRepo.create({
                            userId,
                            ingredientId: ri.ingredientId,
                            quantity: Math.round(amountNeeded * 100) / 100,
                            unit: ri.unit || 'g',
                        });
                        await this.inventoryRepo.save(newInv);
                    }
                }
            }
        }

        return {
            message: isConsumed ? 'Đã đánh dấu đã ăn và tự động khấu trừ tủ lạnh' : 'Đã hủy đánh dấu đã ăn và khôi phục nguyên liệu tủ lạnh',
            isConsumed: item.isConsumed,
        };
    }
}
