import {
  BadRequestException,
  Injectable,
  NotFoundException,
  Logger,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { MealPlan } from './entities/meal-plan.entity';
import { MealPlanItem } from './entities/meal-plan-item.entity';
import { Recipe } from '../recipes/entities/recipe.entity';
import { RecommendationService } from '../recommendation/recommendation.service';
import { CalorieService } from '../recommendation/calorie.service';
import { User } from '../auth/entities/user.entity';
import { Inventory } from '../inventory/entities/inventory.entity';
import { ShoppingList } from '../shopping-list/entities/shopping-list.entity';
import {
  calculateMealPortionWarning,
  getMaxRecommendedDishes,
  getMaxDishesByServings,
} from './meal-portion.util';
import { selectRecipesAvoidingRepeats } from './meal-repeat.util';

@Injectable()
export class MealPlanService {
  private readonly logger = new Logger(MealPlanService.name);
  // Day labels in Vietnamese
  private readonly DAY_LABELS = [
    '',
    'Thứ Hai',
    'Thứ Ba',
    'Thứ Tư',
    'Thứ Năm',
    'Thứ Sáu',
    'Thứ Bảy',
    'Chủ Nhật',
  ];

  private readonly MEAL_TYPES = ['breakfast', 'lunch', 'dinner'];

  constructor(
    @InjectRepository(MealPlan) private planRepo: Repository<MealPlan>,
    @InjectRepository(MealPlanItem) private itemRepo: Repository<MealPlanItem>,
    @InjectRepository(Recipe) private recipeRepo: Repository<Recipe>,
    @InjectRepository(User) private userRepo: Repository<User>,
    @InjectRepository(Inventory) private inventoryRepo: Repository<Inventory>,
    private recommendationService: RecommendationService,
    private calorieService: CalorieService,
  ) {}

  /**
   * Get meal plan for a specific week
   */
  async findByWeek(userId: string, weekStart?: string, warning?: string) {
    const startDate = weekStart
      ? this.parseDateInput(weekStart)
      : this.getMonday(new Date());

    const plan = await this.planRepo.findOne({
      where: { userId, weekStart: startDate },
      relations: ['items', 'items.recipe'],
    });

    if (!plan) return null;

    // Build response with day labels and nutrition data
    const items = plan.items.map((item) => ({
      id: item.id,
      dayOfWeek: this.getDayOfWeekIndex(item.mealDate),
      dayLabel: this.DAY_LABELS[this.getDayOfWeekIndex(item.mealDate)],
      mealDate:
        item.mealDate instanceof Date
          ? this.formatDateInput(item.mealDate)
          : item.mealDate,
      mealType: item.mealType,
      recipe: item.recipe
        ? {
            id: item.recipe.id,
            name: item.recipe.name,
            imageUrl: item.recipe.imageUrl,
            calories: item.recipe.calories,
            protein: Number(item.recipe.protein) || 0,
            carbs: Number(item.recipe.carbs) || 0,
            fat: Number(item.recipe.fat) || 0,
            cookingTime: item.recipe.cookingTime,
          }
        : null,
      calories: item.calories,
      isLocked: item.isLocked,
      isConsumed: item.isConsumed,
    }));

    // Calculate daily nutrition
    const nutrition = this.calculateNutrition(plan.items);

    return {
      id: plan.id,
      weekStart: plan.weekStart,
      weekEnd: plan.weekEnd,
      isAutoGenerated: plan.isAutoGenerated,
      status: plan.status,
      totalCalories: plan.totalCalories,
      dailyAvgCalories: Math.round((plan.totalCalories || 0) / 7),
      items,
      nutrition,
      warning,
    };
  }

  /**
   * Get meal plan by specific ID
   */
  async findById(userId: string, id: string) {
    const plan = await this.planRepo.findOne({
      where: { id, userId },
      relations: ['items', 'items.recipe'],
    });

    if (!plan) return null;

    const items = plan.items.map((item) => ({
      id: item.id,
      dayOfWeek: this.getDayOfWeekIndex(item.mealDate),
      dayLabel: this.DAY_LABELS[this.getDayOfWeekIndex(item.mealDate)],
      mealDate:
        item.mealDate instanceof Date
          ? this.formatDateInput(item.mealDate)
          : item.mealDate,
      mealType: item.mealType,
      recipe: item.recipe
        ? {
            id: item.recipe.id,
            name: item.recipe.name,
            imageUrl: item.recipe.imageUrl,
            calories: item.recipe.calories,
            protein: Number(item.recipe.protein) || 0,
            carbs: Number(item.recipe.carbs) || 0,
            fat: Number(item.recipe.fat) || 0,
            cookingTime: item.recipe.cookingTime,
          }
        : null,
      calories: item.calories,
      isLocked: item.isLocked,
      isConsumed: item.isConsumed,
    }));

    const nutrition = this.calculateNutrition(plan.items);

    return {
      id: plan.id,
      weekStart: plan.weekStart,
      weekEnd: plan.weekEnd,
      isAutoGenerated: plan.isAutoGenerated,
      status: plan.status,
      totalCalories: plan.totalCalories,
      dailyAvgCalories: Math.round((plan.totalCalories || 0) / 7),
      items,
      nutrition,
    };
  }

  /**
   * AI-generate a weekly meal plan
   * Uses greedy sequential selection with diversity enforcement
   */
  async generate(
    userId: string,
    dto: {
      weekStart: string;
      useAntiWaste?: boolean;
      lockedItems?: {
        dayOfWeek?: number;
        mealDate?: string;
        mealType: string;
        recipeId: string;
      }[];
      emptyPlan?: boolean;
      overwrite?: boolean;
      optimizePortions?: boolean;
      prioritizeNew?: boolean;
      noRepeatIn7Days?: boolean;
      avoidRepeatMeals?: boolean;
    },
  ) {
    const weekStart = this.parseDateInput(
      dto.weekStart || this.formatDateInput(this.getMonday(new Date())),
    );
    this.ensureWeekHasCreatableDate(weekStart);
    const weekEnd = new Date(weekStart);
    weekEnd.setDate(weekEnd.getDate() + 6);
    const weekStartValue = this.formatDateInput(weekStart);

    const totalRecipesCount = await this.recipeRepo.count({
      where: { isActive: true, status: 'approved' },
    });
    let databaseWarning: string | undefined = undefined;
    if (totalRecipesCount < 15) {
      databaseWarning =
        'Kho công thức hiện tại quá ít để tạo thực đơn đa dạng hoàn toàn.';
    }

    // Delete existing plan items for this week (if any) and reuse the plan record to avoid foreign key violations with shopping lists
    const existing = await this.planRepo.findOne({
      where: { userId, weekStart: weekStart },
    });

    let plan: MealPlan;
    if (existing) {
      if (dto.overwrite === true) {
        await this.itemRepo.delete({
          mealPlanId: existing.id,
          isLocked: false,
        });
      }
      existing.isAutoGenerated = !dto.emptyPlan;
      existing.status = 'active';
      existing.totalCalories = 0;
      plan = await this.planRepo.save(existing);
    } else {
      // Create new plan
      plan = this.planRepo.create({
        userId,
        weekStart,
        weekEnd,
        isAutoGenerated: !dto.emptyPlan,
        status: 'active',
      });
      await this.planRepo.save(plan);
    }

    if (dto.emptyPlan) {
      if (existing) {
        await this.itemRepo.delete({ mealPlanId: existing.id });
      }
      return this.findByWeek(userId, weekStartValue);
    }

    // Fetch user context for servings
    const user = await this.userRepo.findOne({
      where: { id: userId },
      relations: ['preferences'],
    });
    const servings = user?.preferences?.servings || 4;
    const recentSuggestedRecipes =
      user?.preferences?.recentSuggestedRecipes || [];
    const avoidRepeatMeals =
      dto.noRepeatIn7Days === true || dto.avoidRepeatMeals === true;

    // Track used recipes for diversity
    const usedRecipeIds = new Set<string>();
    const newlySuggested: string[] = [];
    const fallbackState = { hasUsedDuplicates: false };
    const items: MealPlanItem[] = [];
    let totalCalories = 0;

    // Fetch existing items for weekly plan (if any)
    const existingItems = existing
      ? await this.itemRepo.find({
          where: { mealPlanId: existing.id },
          relations: ['recipe'],
        })
      : [];
    const dailyDishCounts = this.buildDailyDishCounts(existingItems);
    if (avoidRepeatMeals) {
      const noRepeatRecipeIds = await this.getRecipeIdsUsedInNoRepeatWindow(
        userId,
        weekStart,
        weekEnd,
      );
      noRepeatRecipeIds.forEach((recipeId) => usedRecipeIds.add(recipeId));
    }

    // Locked items map for quick lookup. Since a slot can have multiple locked items:
    const lockedMap = new Map<string, string[]>();
    if (dto.lockedItems) {
      dto.lockedItems.forEach((li) => {
        let targetDateStr = '';
        if (li.mealDate) {
          targetDateStr = li.mealDate;
        } else if (li.dayOfWeek) {
          const d = new Date(weekStart);
          d.setDate(d.getDate() + (li.dayOfWeek - 1));
          targetDateStr = this.formatDateInput(d);
        }
        if (targetDateStr) {
          const key = `${targetDateStr}-${li.mealType}`;
          const list = lockedMap.get(key) || [];
          list.push(li.recipeId);
          lockedMap.set(key, list);
        }
      });
    }

    // Generate meals: iterate day by day, meal by meal
    for (let i = 0; i < 7; i++) {
      const currentDate = new Date(weekStart);
      currentDate.setDate(currentDate.getDate() + i);
      const dateStr = this.formatDateInput(currentDate);

      if (this.isDateInPast(currentDate)) continue;

      const dayItemsList: MealPlanItem[] = [];
      const currentDayRecipeIds = new Set<string>();
      const currentDayRecipeNames = new Set<string>();
      const currentDayTags: string[] = [];

      const addRecipeToDayContext = (recipe: Recipe) => {
        currentDayRecipeIds.add(recipe.id);
        currentDayRecipeNames.add(recipe.name);
        if (recipe.tags) {
          for (const tag of recipe.tags) {
            const group =
              tag === 'canh' ? 'canh' : tag === 'rau' ? 'rau' : 'main';
            if (!currentDayTags.includes(group)) {
              currentDayTags.push(group);
            }
          }
        }
      };

      for (const mealType of this.MEAL_TYPES) {
        const key = `${dateStr}-${mealType}`;

        // Get existing items for this slot in DB
        const slotExistingItems = existingItems.filter(
          (item) =>
            this.formatDateInput(new Date(item.mealDate)) === dateStr &&
            item.mealType === mealType,
        );
        const recipesAlreadyInSlot = slotExistingItems.filter(
          (item) => item.recipeId !== null,
        );

        // If overwrite is false, and slot has recipes, keep them intact
        if (dto.overwrite !== true && recipesAlreadyInSlot.length > 0) {
          for (const item of recipesAlreadyInSlot) {
            dayItemsList.push(item);
            if (item.recipe) {
              usedRecipeIds.add(item.recipeId);
              addRecipeToDayContext(item.recipe);
            }
          }
          continue;
        }

        const lockedRecipeIds = lockedMap.get(key) || [];
        const slotLockedItems = slotExistingItems.filter(
          (item) => item.isLocked,
        );

        // Add locked items to this slot
        for (const item of slotLockedItems) {
          dayItemsList.push(item);
          if (item.recipe) {
            usedRecipeIds.add(item.recipeId);
            addRecipeToDayContext(item.recipe);
          }
        }

        // Fetch user locked recipes passed in dto.lockedItems
        for (const recipeId of lockedRecipeIds) {
          // Avoid duplicating locked items already pushed
          if (slotLockedItems.some((li) => li.recipeId === recipeId)) continue;

          const recipe = await this.recipeRepo.findOne({
            where: { id: recipeId },
          });
          if (recipe) {
            const item = this.itemRepo.create({
              mealPlanId: plan.id,
              recipeId: recipe.id,
              mealDate: currentDate,
              mealType,
              calories: recipe.calories,
              isLocked: true,
            });
            dayItemsList.push(item);
            usedRecipeIds.add(recipe.id);
            addRecipeToDayContext(recipe);
          }
        }

        const targetCount = this.getTargetDishesCount(servings, mealType);
        const currentCount = dayItemsList.filter(
          (item) => item.mealType === mealType,
        ).length;
        if (currentCount >= targetCount) {
          continue;
        }

        const remainingDailyCapacity =
          getMaxRecommendedDishes(servings) - dayItemsList.length;
        if (remainingDailyCapacity <= 0) {
          continue;
        }

        const neededCount = Math.min(
          targetCount - currentCount,
          remainingDailyCapacity,
        );

        // Use AI to get recommendations for this slot
        const recs = await this.recommendationService.getRecommendations(
          userId,
          mealType,
          avoidRepeatMeals ? 100 : 30, // request more options to avoid repeat fallback too early
          dto.useAntiWaste !== false,
          {
            prioritizeNew: dto.prioritizeNew,
            noRepeatIn7Days: avoidRepeatMeals,
            currentDayRecipeIds: Array.from(currentDayRecipeIds),
            currentDayRecipeNames: Array.from(currentDayRecipeNames),
            currentDayTags,
            recentSuggestedNames: recentSuggestedRecipes,
            weeklyUsedRecipeIds: Array.from(usedRecipeIds),
          },
        );
        this.logRepeatDebug(
          usedRecipeIds,
          recs.recommendations,
          avoidRepeatMeals,
        );

        const selectionContext = {
          currentDayRecipeIds,
          currentDayRecipeNames,
          weeklyUsedRecipeIds: usedRecipeIds,
          recentSuggestedRecipes,
          prioritizeNew: dto.prioritizeNew,
          noRepeatIn7Days: avoidRepeatMeals,
        };

        // Select recipes based on classification and fallback rules
        const selectedRecipes = this.selectRecipesForSlotWithFallback(
          recs.recommendations,
          neededCount,
          selectionContext,
          fallbackState,
          dayItemsList,
          dateStr,
          mealType,
        );

        for (const recipe of selectedRecipes) {
          const item = this.itemRepo.create({
            mealPlanId: plan.id,
            recipeId: recipe.id,
            mealDate: currentDate,
            mealType,
            calories: recipe.calories,
            isLocked: false,
          });
          dayItemsList.push(item);
          usedRecipeIds.add(recipe.id);
          addRecipeToDayContext(recipe);
          newlySuggested.push(recipe.name);
        }
      }

      // Evaluate calories for this day
      let dayCalories = dayItemsList.reduce(
        (sum, item) => sum + (item.calories || 0),
        0,
      );
      const dailyCalTarget = user?.dailyCalorieTarget || 2000;

      // If calories are insufficient, prioritize scaling portions first (Tăng khẩu phần)
      if (dayCalories < dailyCalTarget && dayCalories > 0) {
        const ratio = dailyCalTarget / dayCalories;
        // Scale up existing dishes by up to 1.3x to balance nutrition
        const scale = Math.min(ratio, 1.3);
        if (scale > 1.0) {
          for (const item of dayItemsList) {
            item.calories = Math.round(item.calories * scale);
            item.notes = 'Tăng khẩu phần';
          }
          dayCalories = dayItemsList.reduce(
            (sum, item) => sum + (item.calories || 0),
            0,
          );
        }
      }

      // If calories are STILL insufficient, prioritize adding extra side dishes (Thêm món phụ)
      // up to the maximum recommended dishes for this serving count.
      const maxRecommended = getMaxRecommendedDishes(servings);
      if (
        dayCalories < dailyCalTarget &&
        dayItemsList.length < maxRecommended
      ) {
        // Loop to add side dishes until target met or max reached
        // We add side dishes to lunch first, then dinner, then breakfast
        const mealsToAdd = ['lunch', 'dinner', 'breakfast'];
        let mealIndex = 0;

        while (
          dayCalories < dailyCalTarget &&
          dayItemsList.length < maxRecommended
        ) {
          const mealType = mealsToAdd[mealIndex % mealsToAdd.length];
          mealIndex++;

          const recs = await this.recommendationService.getRecommendations(
            userId,
            mealType,
            avoidRepeatMeals ? 100 : 30,
            dto.useAntiWaste !== false,
            {
              prioritizeNew: dto.prioritizeNew,
              noRepeatIn7Days: avoidRepeatMeals,
              currentDayRecipeIds: Array.from(currentDayRecipeIds),
              currentDayRecipeNames: Array.from(currentDayRecipeNames),
              currentDayTags,
              recentSuggestedNames: recentSuggestedRecipes,
              weeklyUsedRecipeIds: Array.from(usedRecipeIds),
            },
          );
          this.logRepeatDebug(
            usedRecipeIds,
            recs.recommendations,
            avoidRepeatMeals,
          );

          const selectionContext = {
            currentDayRecipeIds,
            currentDayRecipeNames,
            weeklyUsedRecipeIds: usedRecipeIds,
            recentSuggestedRecipes,
            prioritizeNew: dto.prioritizeNew,
            noRepeatIn7Days: avoidRepeatMeals,
          };

          const selectedRecipes = this.selectRecipesForSlotWithFallback(
            recs.recommendations,
            1,
            selectionContext,
            fallbackState,
            dayItemsList,
            dateStr,
            mealType,
          );

          if (selectedRecipes.length === 0) break; // no more recipes to recommend

          const recipe = selectedRecipes[0];
          const item = this.itemRepo.create({
            mealPlanId: plan.id,
            recipeId: recipe.id,
            mealDate: currentDate,
            mealType,
            calories: recipe.calories,
            isLocked: false,
            notes: 'Món phụ',
          });

          dayItemsList.push(item);
          usedRecipeIds.add(recipe.id);
          addRecipeToDayContext(recipe);
          newlySuggested.push(recipe.name);
          dayCalories += recipe.calories;
        }
      }

      // Add all day items to weekly list and update total calories
      for (const item of dayItemsList) {
        items.push(item);
        totalCalories += item.calories || 0;
      }
    }

    // Prepend new suggested recipes to user history and save
    if (newlySuggested.length > 0 && user?.preferences) {
      const updatedList = Array.from(
        new Set([...newlySuggested, ...recentSuggestedRecipes]),
      );
      user.preferences.recentSuggestedRecipes = updatedList.slice(0, 50);
      await this.userRepo.manager.save(user.preferences);
    }

    // Save only newly created items (where id is undefined/null)
    const newItems = items.filter((item) => !item.id);
    if (newItems.length > 0) {
      await this.itemRepo.save(newItems);
    }

    // Update total calories
    plan.totalCalories = totalCalories;
    await this.planRepo.save(plan);

    if (dto.optimizePortions === true) {
      const datesToOptimize = Array.from({ length: 7 }, (_, i) => {
        const date = new Date(weekStart);
        date.setDate(date.getDate() + i);
        return date;
      });
      await this.optimizeMealPlanItemsForPortions(
        plan.id,
        datesToOptimize,
        servings,
      );
      await this.recalculateTotalCalories(plan.id);
    }

    return this.findByWeek(
      userId,
      weekStartValue,
      databaseWarning
        ? databaseWarning
        : fallbackState.hasUsedDuplicates
          ? 'Không đủ món để tránh lặp hoàn toàn. Một số món được tái sử dụng.'
          : undefined,
    );
  }

  async swapRecipe(
    userId: string,
    planId: string,
    itemId: string,
    recipeId: string,
  ) {
    const item = await this.itemRepo.findOne({
      where: { id: itemId, mealPlanId: planId },
    });
    if (!item) throw new NotFoundException('Meal plan item not found');

    const recipe = await this.recipeRepo.findOne({ where: { id: recipeId } });
    if (!recipe) throw new NotFoundException('Recipe not found');

    // Check if the recipe is already used in another slot on the same day
    const existingItemsOnDay = await this.itemRepo.find({
      where: {
        mealPlanId: planId,
        mealDate: item.mealDate,
      },
    });

    // Exclude the current item from validation check
    const otherItemsOnDay = existingItemsOnDay.filter((i) => i.id !== itemId);
    const hasDuplicate = otherItemsOnDay.some((i) => i.recipeId === recipe.id);

    if (hasDuplicate) {
      throw new BadRequestException(
        'Món ăn này đã có trong thực đơn của ngày hôm đó.',
      );
    }

    item.recipeId = recipe.id;
    item.calories = recipe.calories;
    await this.itemRepo.save(item);

    // Recalculate total calories
    await this.recalculateTotalCalories(planId);

    return {
      id: item.id,
      dayOfWeek: this.getDayOfWeekIndex(item.mealDate),
      mealDate:
        item.mealDate instanceof Date
          ? this.formatDateInput(item.mealDate)
          : item.mealDate,
      mealType: item.mealType,
      recipe: {
        id: recipe.id,
        name: recipe.name,
        calories: recipe.calories,
        protein: Number(recipe.protein) || 0,
        carbs: Number(recipe.carbs) || 0,
        fat: Number(recipe.fat) || 0,
      },
      calories: recipe.calories,
      isLocked: item.isLocked,
      isConsumed: item.isConsumed,
    };
  }

  /**
   * Add or update a specific meal slot in a plan by day and mealType
   */
  async setMealSlot(
    userId: string,
    mealDate: string,
    mealType: string,
    recipeId: string,
    overwrite = false,
  ) {
    const targetDate = this.parseDateInput(mealDate);
    this.ensureDateIsCreatable(targetDate);
    const startDate = this.getMonday(targetDate);

    // 1. Get or create meal plan for this week
    let plan = await this.planRepo.findOne({
      where: { userId, weekStart: startDate },
    });
    if (!plan) {
      const endDate = new Date(startDate);
      endDate.setDate(endDate.getDate() + 6);

      plan = this.planRepo.create({
        userId,
        weekStart: startDate,
        weekEnd: endDate,
        isAutoGenerated: false,
        status: 'active',
        totalCalories: 0,
      });
      await this.planRepo.save(plan);
    }

    // 2. Fetch the recipe to get calories
    const recipe = await this.recipeRepo.findOne({ where: { id: recipeId } });
    if (!recipe) throw new NotFoundException('Recipe not found');

    // Check if there are already items in this slot (locked or non-locked)
    const existingItems = await this.itemRepo.find({
      where: { mealPlanId: plan.id, mealDate: targetDate, mealType },
    });

    if (!overwrite) {
      const isExactRecipe = existingItems.some(
        (item) => item.recipeId === recipe.id,
      );
      if (isExactRecipe) {
        return this.findByWeek(userId, this.formatDateInput(startDate));
      }
    }

    if (overwrite && existingItems.length > 0) {
      await this.itemRepo.remove(existingItems);
    }

    // Create a new item for this slot. This allows one meal to contain many dishes.
    const item = this.itemRepo.create({
      mealPlanId: plan.id,
      mealDate: targetDate,
      mealType,
      recipeId: recipe.id,
      calories: recipe.calories,
      isLocked: true, // Keep locked so AI generation won't overwrite it
    });
    await this.itemRepo.save(item);

    // Recalculate total calories
    await this.recalculateTotalCalories(plan.id);

    return this.findByWeek(userId, this.formatDateInput(startDate));
  }

  async addMealSlotRecipes(
    userId: string,
    mealDate: string,
    mealType: string,
    recipeIds: string[],
    overwrite = false,
  ) {
    const uniqueRecipeIds = Array.from(new Set(recipeIds.filter(Boolean)));
    if (uniqueRecipeIds.length === 0) {
      throw new BadRequestException('Vui lòng chọn ít nhất một món ăn');
    }

    let result = null;
    for (const [index, recipeId] of uniqueRecipeIds.entries()) {
      result = await this.setMealSlot(
        userId,
        mealDate,
        mealType,
        recipeId,
        overwrite && index === 0,
      );
    }

    return result;
  }

  /**
   * Generate or update recipes specifically for a set of days (leaving other days unchanged)
   */
  async generateForDays(
    userId: string,
    dto: {
      weekStart?: string;
      days?: number[];
      mealDates?: string[];
      useAntiWaste?: boolean;
      mealType?: string;
      overwrite?: boolean;
      optimizePortions?: boolean;
      prioritizeNew?: boolean;
      noRepeatIn7Days?: boolean;
      avoidRepeatMeals?: boolean;
    },
  ) {
    let mealDates = dto.mealDates;
    if ((!mealDates || mealDates.length === 0) && dto.weekStart && dto.days) {
      const start = this.parseDateInput(dto.weekStart);
      mealDates = dto.days.map((day) => {
        const d = new Date(start);
        d.setDate(d.getDate() + (day - 1));
        return this.formatDateInput(d);
      });
    }

    if (!mealDates || mealDates.length === 0) {
      throw new BadRequestException(
        'Vui lòng chọn ít nhất một ngày để tạo thực đơn.',
      );
    }

    const parsedDates = mealDates.map((d) => this.parseDateInput(d));
    parsedDates.forEach((date) => this.ensureDateIsCreatable(date));

    // Find weekStart from the first date
    const weekStart = this.getMonday(parsedDates[0]);

    const totalRecipesCount = await this.recipeRepo.count({
      where: { isActive: true, status: 'approved' },
    });
    let databaseWarning: string | undefined = undefined;
    if (totalRecipesCount < 15) {
      databaseWarning =
        'Kho công thức hiện tại quá ít để tạo thực đơn đa dạng hoàn toàn.';
    }

    // 1. Get or create the meal plan for this week
    let plan = await this.planRepo.findOne({
      where: { userId, weekStart },
    });

    if (!plan) {
      const startDate = new Date(weekStart);
      const endDate = new Date(startDate);
      endDate.setDate(endDate.getDate() + 6);

      plan = this.planRepo.create({
        userId,
        weekStart: startDate,
        weekEnd: endDate,
        isAutoGenerated: true,
        status: 'active',
        totalCalories: 0,
      });
      await this.planRepo.save(plan);
    }
    if (dto.optimizePortions === true) {
      const user = await this.userRepo.findOne({
        where: { id: userId },
        relations: ['preferences'],
      });
      const servings = user?.preferences?.servings || 4;
      const dailyCalorieTarget = user?.dailyCalorieTarget || 2000;

      const optResult = await this.optimizeMealPlanItemsForPortions(
        plan.id,
        parsedDates,
        servings,
        dailyCalorieTarget,
      );

      await this.recalculateTotalCalories(plan.id);

      const planData = await this.findByWeek(
        userId,
        this.formatDateInput(weekStart),
      );

      return {
        ...planData,
        optimizationDetails: optResult,
      };
    } else if (dto.overwrite === true) {
      // Delete existing non-locked items for the specified dates and mealType (if provided) so we can regenerate them
      const deleteCriteria: any = {
        mealPlanId: plan.id,
        mealDate: In(parsedDates.map((d) => this.formatDateInput(d))),
        isLocked: false,
      };
      if (dto.mealType) {
        deleteCriteria.mealType = dto.mealType;
      }
      await this.itemRepo.delete(deleteCriteria);
    }

    // Fetch user context for servings
    const user = await this.userRepo.findOne({
      where: { id: userId },
      relations: ['preferences'],
    });
    const servings = user?.preferences?.servings || 4;
    const recentSuggestedRecipes =
      user?.preferences?.recentSuggestedRecipes || [];
    const avoidRepeatMeals =
      dto.noRepeatIn7Days !== false && dto.avoidRepeatMeals !== false;

    // 2. Track used recipe IDs in this plan to keep it diverse
    const existingItems = await this.itemRepo.find({
      where: { mealPlanId: plan.id },
      relations: ['recipe'],
    });
    const usedRecipeIds = new Set<string>(
      existingItems.filter((item) => item.recipe).map((item) => item.recipe.id),
    );
    const dailyDishCounts = this.buildDailyDishCounts(existingItems);
    if (avoidRepeatMeals) {
      const weekEnd = new Date(weekStart);
      weekEnd.setDate(weekEnd.getDate() + 6);
      const noRepeatRecipeIds = await this.getRecipeIdsUsedInNoRepeatWindow(
        userId,
        weekStart,
        weekEnd,
      );
      noRepeatRecipeIds.forEach((recipeId) => usedRecipeIds.add(recipeId));
    }
    const newlySuggested: string[] = [];
    const fallbackState = { hasUsedDuplicates: false };

    // 3. Generate meals for each specified day and meal type
    const mealTypesToGenerate = dto.mealType ? [dto.mealType] : this.MEAL_TYPES;
    for (const date of parsedDates) {
      const dateStr = this.formatDateInput(date);
      const dayItemsList: MealPlanItem[] = [];
      const currentDayRecipeIds = new Set<string>();
      const currentDayRecipeNames = new Set<string>();
      const currentDayTags: string[] = [];

      const addRecipeToDayContext = (recipe: Recipe) => {
        currentDayRecipeIds.add(recipe.id);
        currentDayRecipeNames.add(recipe.name);
        if (recipe.tags) {
          for (const tag of recipe.tags) {
            const group =
              tag === 'canh' ? 'canh' : tag === 'rau' ? 'rau' : 'main';
            if (!currentDayTags.includes(group)) {
              currentDayTags.push(group);
            }
          }
        }
      };

      // Load existing items for this specific date
      const dateExistingItems = await this.itemRepo.find({
        where: { mealPlanId: plan.id, mealDate: date },
        relations: ['recipe'],
      });

      if (dto.overwrite === true) {
        // Keep only locked items
        const lockedItems = dateExistingItems.filter((item) => item.isLocked);
        for (const item of lockedItems) {
          dayItemsList.push(item);
          if (item.recipe) {
            usedRecipeIds.add(item.recipeId);
            addRecipeToDayContext(item.recipe);
          }
        }
      } else {
        // Keep all existing items initially
        for (const item of dateExistingItems) {
          dayItemsList.push(item);
          if (item.recipe) {
            usedRecipeIds.add(item.recipeId);
            addRecipeToDayContext(item.recipe);
          }
        }

        // --- DUPLICATE DETECTION AND REPLACEMENT ---
        const recipeOccurrences = new Map<string, number>();
        for (const item of dayItemsList) {
          if (item.recipeId) {
            recipeOccurrences.set(
              item.recipeId,
              (recipeOccurrences.get(item.recipeId) || 0) + 1,
            );
          }
        }

        for (const [recipeId, count] of recipeOccurrences.entries()) {
          if (count > 1) {
            const itemsForRecipe = dayItemsList.filter(
              (item) => item.recipeId === recipeId,
            );
            // Sort so locked ones come first
            itemsForRecipe.sort((a, b) => (a.isLocked ? -1 : 1));
            // Keep the first one, try to replace the others that are not locked
            for (let j = 1; j < itemsForRecipe.length; j++) {
              const itemToReplace = itemsForRecipe[j];
              if (!itemToReplace.isLocked && itemToReplace.recipe) {
                const recs =
                  await this.recommendationService.getRecommendations(
                    userId,
                    itemToReplace.mealType,
                    avoidRepeatMeals ? 100 : 30,
                    dto.useAntiWaste !== false,
                    {
                      prioritizeNew: dto.prioritizeNew,
                      noRepeatIn7Days: avoidRepeatMeals,
                      currentDayRecipeIds: Array.from(currentDayRecipeIds),
                      currentDayRecipeNames: Array.from(currentDayRecipeNames),
                      currentDayTags,
                      recentSuggestedNames: recentSuggestedRecipes,
                      weeklyUsedRecipeIds: Array.from(usedRecipeIds),
                    },
                  );

                const selectionContext = {
                  currentDayRecipeIds,
                  currentDayRecipeNames,
                  weeklyUsedRecipeIds: usedRecipeIds,
                  recentSuggestedRecipes,
                  prioritizeNew: dto.prioritizeNew,
                  noRepeatIn7Days: avoidRepeatMeals,
                };

                const selectedRecipes = this.selectRecipesForSlotWithFallback(
                  recs.recommendations,
                  1,
                  selectionContext,
                  fallbackState,
                  dayItemsList,
                  dateStr,
                  itemToReplace.mealType,
                );

                if (selectedRecipes.length > 0) {
                  const newRecipe = selectedRecipes[0];

                  // Update item
                  itemToReplace.recipeId = newRecipe.id;
                  itemToReplace.recipe = newRecipe;
                  itemToReplace.calories = newRecipe.calories;

                  // Update contexts
                  usedRecipeIds.add(newRecipe.id);
                  addRecipeToDayContext(newRecipe);
                  newlySuggested.push(newRecipe.name);
                }
              }
            }
          }
        }
      }

      // Re-initialize day context after potential replacements
      currentDayRecipeIds.clear();
      currentDayRecipeNames.clear();
      currentDayTags.length = 0;
      for (const item of dayItemsList) {
        if (item.recipe) {
          addRecipeToDayContext(item.recipe);
        }
      }

      // --- ADD MISSING DISHES ---
      const currentDishCount = dayItemsList.filter(
        (item) => item.recipeId,
      ).length;
      const maxDishCount = getMaxDishesByServings(servings);
      const missingCount = maxDishCount - currentDishCount;

      const addedCounts = { breakfast: 0, lunch: 0, dinner: 0 };
      const selectedRecipesLog: any[] = [];

      if (missingCount > 0) {
        for (let i = 0; i < missingCount; i++) {
          let bestMealType = null;
          let maxDiff = -Infinity;

          const checkOrder = ['dinner', 'lunch', 'breakfast'];
          for (const mt of checkOrder) {
            const target = this.getTargetDishesCount(servings, mt);
            const current = dayItemsList.filter(
              (item) => item.mealType === mt,
            ).length;
            const added = addedCounts[mt];
            const diff = target - (current + added);
            if (diff > maxDiff) {
              maxDiff = diff;
              bestMealType = mt;
            }
          }
          if (bestMealType) {
            addedCounts[bestMealType]++;
          }
        }

        // Generate the balancing dishes
        for (const mealType of this.MEAL_TYPES) {
          const neededCount = addedCounts[mealType];
          if (neededCount <= 0) continue;

          const recs = await this.recommendationService.getRecommendations(
            userId,
            mealType,
            avoidRepeatMeals ? 100 : 30,
            dto.useAntiWaste !== false,
            {
              prioritizeNew: dto.prioritizeNew,
              noRepeatIn7Days: avoidRepeatMeals,
              currentDayRecipeIds: Array.from(currentDayRecipeIds),
              currentDayRecipeNames: Array.from(currentDayRecipeNames),
              currentDayTags,
              recentSuggestedNames: recentSuggestedRecipes,
              weeklyUsedRecipeIds: Array.from(usedRecipeIds),
            },
          );

          const selectionContext = {
            currentDayRecipeIds,
            currentDayRecipeNames,
            weeklyUsedRecipeIds: usedRecipeIds,
            recentSuggestedRecipes,
            prioritizeNew: dto.prioritizeNew,
            noRepeatIn7Days: avoidRepeatMeals,
          };

          const selectedRecipes = this.selectRecipesForSlotWithFallback(
            recs.recommendations,
            neededCount,
            selectionContext,
            fallbackState,
            dayItemsList,
            dateStr,
            mealType,
          );

          for (const recipe of selectedRecipes) {
            const item = this.itemRepo.create({
              mealPlanId: plan.id,
              recipeId: recipe.id,
              mealDate: date,
              mealType,
              calories: recipe.calories,
              isLocked: false,
            });
            dayItemsList.push(item);
            usedRecipeIds.add(recipe.id);
            addRecipeToDayContext(recipe);
            newlySuggested.push(recipe.name);
            selectedRecipesLog.push({
              id: recipe.id,
              name: recipe.name,
              mealType,
            });
          }
        }
      }

      // --- LOG DEBUG INFORMATION ---
      const finalRecipeOccurrences = new Map<string, number>();
      for (const item of dayItemsList) {
        if (item.recipeId && item.recipe) {
          finalRecipeOccurrences.set(
            item.recipe.name,
            (finalRecipeOccurrences.get(item.recipe.name) || 0) + 1,
          );
        }
      }
      const finalDuplicated: string[] = [];
      for (const [name, count] of finalRecipeOccurrences.entries()) {
        if (count > 1) {
          finalDuplicated.push(name);
        }
      }

      console.log('[AI Suggest Debug Log]', {
        servings,
        maxDishCount,
        currentDishCount,
        missingCount,
        usedRecipeIds: Array.from(usedRecipeIds),
        selectedRecipes: selectedRecipesLog,
        duplicatedRecipes: finalDuplicated,
      });

      // Evaluate calories for this day
      let dayCalories = dayItemsList.reduce(
        (sum, item) => sum + (item.calories || 0),
        0,
      );
      const dailyCalTarget = user?.dailyCalorieTarget || 2000;

      // If calories are insufficient, prioritize scaling portions first (Tăng khẩu phần)
      if (dayCalories < dailyCalTarget && dayCalories > 0) {
        const ratio = dailyCalTarget / dayCalories;
        const scale = Math.min(ratio, 1.3);
        if (scale > 1.0) {
          for (const item of dayItemsList) {
            item.calories = Math.round(item.calories * scale);
            item.notes = 'Tăng khẩu phần';
          }
          dayCalories = dayItemsList.reduce(
            (sum, item) => sum + (item.calories || 0),
            0,
          );
        }
      }

      // If calories are STILL insufficient, prioritize adding extra side dishes (Thêm món phụ)
      const maxRecommended = getMaxRecommendedDishes(servings);
      if (
        dayCalories < dailyCalTarget &&
        dayItemsList.length < maxRecommended
      ) {
        const mealsToAdd = ['lunch', 'dinner', 'breakfast'];
        let mealIndex = 0;

        while (
          dayCalories < dailyCalTarget &&
          dayItemsList.length < maxRecommended
        ) {
          const mealType = mealsToAdd[mealIndex % mealsToAdd.length];
          mealIndex++;

          const recs = await this.recommendationService.getRecommendations(
            userId,
            mealType,
            avoidRepeatMeals ? 100 : 30,
            dto.useAntiWaste !== false,
            {
              prioritizeNew: dto.prioritizeNew,
              noRepeatIn7Days: avoidRepeatMeals,
              currentDayRecipeIds: Array.from(currentDayRecipeIds),
              currentDayRecipeNames: Array.from(currentDayRecipeNames),
              currentDayTags,
              recentSuggestedNames: recentSuggestedRecipes,
              weeklyUsedRecipeIds: Array.from(usedRecipeIds),
            },
          );
          this.logRepeatDebug(
            usedRecipeIds,
            recs.recommendations,
            avoidRepeatMeals,
          );

          const selectionContext = {
            currentDayRecipeIds,
            currentDayRecipeNames,
            weeklyUsedRecipeIds: usedRecipeIds,
            recentSuggestedRecipes,
            prioritizeNew: dto.prioritizeNew,
            noRepeatIn7Days: avoidRepeatMeals,
          };

          const selectedRecipes = this.selectRecipesForSlotWithFallback(
            recs.recommendations,
            1,
            selectionContext,
            fallbackState,
            dayItemsList,
            dateStr,
            mealType,
          );

          if (selectedRecipes.length === 0) break;

          const recipe = selectedRecipes[0];
          const item = this.itemRepo.create({
            mealPlanId: plan.id,
            recipeId: recipe.id,
            mealDate: date,
            mealType,
            calories: recipe.calories,
            isLocked: false,
            notes: 'Món phụ',
          });

          dayItemsList.push(item);
          usedRecipeIds.add(recipe.id);
          addRecipeToDayContext(recipe);
          newlySuggested.push(recipe.name);
          dayCalories += recipe.calories;
        }
      }

      // Save/update items for this day
      // Remove existing items for this day from DB that are not in dayItemsList
      const dbItemsForDay = await this.itemRepo.find({
        where: { mealPlanId: plan.id, mealDate: date },
      });
      const itemsToRemove = dbItemsForDay.filter(
        (dbItem) => !dayItemsList.some((item) => item.id === dbItem.id),
      );
      if (itemsToRemove.length > 0) {
        await this.itemRepo.remove(itemsToRemove);
      }

      // Save new or updated items
      for (const item of dayItemsList) {
        await this.itemRepo.save(item);
      }
    }

    // Prepend new suggested ones and keep unique names
    if (newlySuggested.length > 0 && user?.preferences) {
      const updatedList = Array.from(
        new Set([...newlySuggested, ...recentSuggestedRecipes]),
      );
      user.preferences.recentSuggestedRecipes = updatedList.slice(0, 50);
      await this.userRepo.manager.save(user.preferences);
    }

    // 4. Recalculate daily average calories and total calories
    await this.recalculateTotalCalories(plan.id);

    return this.findByWeek(
      userId,
      this.formatDateInput(weekStart),
      databaseWarning
        ? databaseWarning
        : fallbackState.hasUsedDuplicates
          ? 'Không đủ món để tránh lặp hoàn toàn. Một số món được tái sử dụng.'
          : undefined,
    );
  }

  /**
   * Lock/unlock a meal slot
   */
  async toggleLock(
    userId: string,
    planId: string,
    itemId: string,
    isLocked: boolean,
  ) {
    const plan = await this.planRepo.findOne({ where: { id: planId, userId } });
    if (!plan) throw new NotFoundException('Meal plan not found');

    const item = await this.itemRepo.findOne({
      where: { id: itemId, mealPlanId: planId },
    });
    if (!item) throw new NotFoundException('Meal plan item not found');

    item.isLocked = isLocked;
    await this.itemRepo.save(item);
    return { id: item.id, isLocked: item.isLocked };
  }

  async removeItem(userId: string, planId: string, itemId: string) {
    const plan = await this.planRepo.findOne({ where: { id: planId, userId } });
    if (!plan) throw new NotFoundException('Meal plan not found');

    const item = await this.itemRepo.findOne({
      where: { id: itemId, mealPlanId: planId },
    });
    if (!item) throw new NotFoundException('Meal plan item not found');

    await this.itemRepo.remove(item);

    // Recalculate total calories
    await this.recalculateTotalCalories(planId);

    return { message: 'Meal plan item removed' };
  }

  /**
   * Delete a meal plan
   */
  async remove(userId: string, planId: string) {
    const plan = await this.planRepo.findOne({ where: { id: planId, userId } });
    if (!plan) throw new NotFoundException('Meal plan not found');

    // Disassociate any shopping lists referencing this plan to avoid foreign key violation
    await this.planRepo.manager.update(
      ShoppingList,
      { mealPlanId: planId },
      { mealPlanId: null },
    );

    // Delete related items first to ensure foreign key constraint satisfaction in case ON DELETE CASCADE is not synced
    await this.itemRepo.delete({ mealPlanId: planId });

    await this.planRepo.remove(plan);
    return { message: 'Meal plan deleted' };
  }

  /**
   * Get nutrition breakdown for charts (Chart.js data)
   */
  async getNutrition(userId: string, planId: string) {
    const plan = await this.planRepo.findOne({
      where: { id: planId, userId },
      relations: ['items', 'items.recipe'],
    });
    if (!plan) throw new NotFoundException('Meal plan not found');

    const user = await this.userRepo.findOne({ where: { id: userId } });
    const daily = this.calculateNutrition(plan.items);
    const totalDishes = daily.reduce((sum, d) => sum + d.dishCount, 0);

    // Calculate weekly averages
    const weeklyAvg = {
      calories: Math.round(daily.reduce((sum, d) => sum + d.calories, 0) / 7),
      protein:
        Math.round((daily.reduce((sum, d) => sum + d.protein, 0) / 7) * 10) /
        10,
      carbs:
        Math.round((daily.reduce((sum, d) => sum + d.carbs, 0) / 7) * 10) / 10,
      fat: Math.round((daily.reduce((sum, d) => sum + d.fat, 0) / 7) * 10) / 10,
    };

    // Macro distribution percentages
    const totalMacroCalories =
      weeklyAvg.protein * 4 + weeklyAvg.carbs * 4 + weeklyAvg.fat * 9;
    const macroDistribution = {
      proteinPercent:
        totalMacroCalories > 0
          ? Math.round(
              ((weeklyAvg.protein * 4) / totalMacroCalories) * 100 * 10,
            ) / 10
          : 0,
      carbsPercent:
        totalMacroCalories > 0
          ? Math.round(
              ((weeklyAvg.carbs * 4) / totalMacroCalories) * 100 * 10,
            ) / 10
          : 0,
      fatPercent:
        totalMacroCalories > 0
          ? Math.round(((weeklyAvg.fat * 9) / totalMacroCalories) * 100 * 10) /
            10
          : 0,
    };

    return {
      calorieTarget: user?.dailyCalorieTarget || 0,
      daily,
      weeklyAvg,
      macroDistribution,
      totalDishes,
    };
  }

  private calculateNutrition(items: MealPlanItem[]) {
    const dailyMap = new Map<
      number,
      {
        calories: number;
        protein: number;
        carbs: number;
        fat: number;
        dishCount: number;
      }
    >();

    for (let d = 1; d <= 7; d++) {
      dailyMap.set(d, {
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        dishCount: 0,
      });
    }

    for (const item of items) {
      if (item.recipe) {
        const dayOfWeek = this.getDayOfWeekIndex(item.mealDate);
        const day = dailyMap.get(dayOfWeek);
        if (day) {
          day.calories += item.recipe.calories || 0;
          day.protein += Number(item.recipe.protein) || 0;
          day.carbs += Number(item.recipe.carbs) || 0;
          day.fat += Number(item.recipe.fat) || 0;
          day.dishCount += 1;
        }
      }
    }

    return Array.from(dailyMap.entries()).map(([day, data]) => ({
      day,
      label: this.DAY_LABELS[day],
      ...data,
    }));
  }

  private async recalculateTotalCalories(planId: string) {
    const items = await this.itemRepo.find({ where: { mealPlanId: planId } });
    const total = items.reduce((sum, item) => sum + (item.calories || 0), 0);
    await this.planRepo.update(planId, { totalCalories: total });
  }

  private getMonday(d: Date): Date {
    const target = this.dateOnly(d);
    const day = target.getDay();
    const diff = target.getDate() - day + (day === 0 ? -6 : 1);
    target.setDate(diff);
    return target;
  }

  private parseDateInput(value: string | Date): Date {
    if (value instanceof Date) return this.dateOnly(value);

    const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(value);
    if (!match) {
      const parsed = new Date(value);
      if (Number.isNaN(parsed.getTime())) {
        throw new BadRequestException(
          'Ngày không hợp lệ. Vui lòng dùng định dạng YYYY-MM-DD.',
        );
      }
      return this.dateOnly(parsed);
    }

    return new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
  }

  private dateOnly(date: Date): Date {
    return new Date(date.getFullYear(), date.getMonth(), date.getDate());
  }

  private formatDateInput(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  private getDayOfWeekIndex(date: Date | string): number {
    const d = new Date(date);
    const day = d.getDay(); // 0 = Sunday, 1 = Monday, ..., 6 = Saturday
    return day === 0 ? 7 : day;
  }

  private isDateInPast(date: Date): boolean {
    return this.dateOnly(date) < this.dateOnly(new Date());
  }

  private ensureDateIsCreatable(date: Date) {
    if (this.isDateInPast(date)) {
      throw new BadRequestException(
        'Không thể tạo hoặc chỉnh sửa thực đơn cho ngày đã qua.',
      );
    }
  }

  private ensureWeekHasCreatableDate(weekStart: Date) {
    const weekEnd = new Date(weekStart);
    weekEnd.setDate(weekEnd.getDate() + 6);
    if (weekEnd < this.dateOnly(new Date())) {
      throw new BadRequestException('Không thể tạo thực đơn cho tuần đã qua.');
    }
  }

  private buildDailyDishCounts(items: MealPlanItem[]) {
    const counts = new Map<string, number>();

    for (const item of items) {
      if (!item.recipeId) continue;
      const dateStr = this.formatDateInput(new Date(item.mealDate));
      counts.set(dateStr, (counts.get(dateStr) || 0) + 1);
    }

    return counts;
  }

  private getRemainingDailyDishCapacity(
    dailyDishCounts: Map<string, number>,
    dateStr: string,
    servings: number,
  ) {
    return Math.max(
      0,
      getMaxRecommendedDishes(servings) - (dailyDishCounts.get(dateStr) || 0),
    );
  }

  private incrementDailyDishCount(
    dailyDishCounts: Map<string, number>,
    dateStr: string,
  ) {
    dailyDishCounts.set(dateStr, (dailyDishCounts.get(dateStr) || 0) + 1);
  }

  private async getRecipeIdsUsedInNoRepeatWindow(
    userId: string,
    weekStart: Date,
    weekEnd: Date,
  ) {
    const historyStart = new Date(weekStart);
    historyStart.setDate(historyStart.getDate() - 7);

    const rows = await this.itemRepo
      .createQueryBuilder('item')
      .innerJoin('item.mealPlan', 'plan')
      .where('plan."userId" = :userId', { userId })
      .andWhere('item.meal_date BETWEEN :startDate AND :endDate', {
        startDate: this.formatDateInput(historyStart),
        endDate: this.formatDateInput(weekEnd),
      })
      .andWhere('item."recipeId" IS NOT NULL')
      .select('DISTINCT item."recipeId"', 'recipeId')
      .getRawMany<{ recipeId: string }>();

    return new Set(rows.map((row) => row.recipeId).filter(Boolean));
  }

  private logRepeatDebug(
    usedRecipeIds: Set<string>,
    recommendations: any[],
    noRepeatIn7Days?: boolean,
  ) {
    if (!noRepeatIn7Days) return;

    const recommendedRecipes = recommendations
      .map((recommendation) => recommendation?.recipe || recommendation)
      .filter((recipe) => recipe?.id);
    const availableRecipes = recommendedRecipes
      .filter((recipe) => !usedRecipeIds.has(recipe.id))
      .map((recipe) => ({ id: recipe.id, name: recipe.name }));

    console.log('Used recipes', Array.from(usedRecipeIds));
    console.log('Available recipes', availableRecipes);
  }

  private getTargetDishesPerDay(servings: number): number {
    return this.MEAL_TYPES.reduce(
      (total, mealType) =>
        total + this.getTargetDishesCount(servings, mealType),
      0,
    );
  }

  private scoreMealPlanItemForKeeping(
    item: MealPlanItem,
    dayItems: MealPlanItem[],
  ): number {
    const recipe = item.recipe;
    if (!recipe) return 0;

    let score = 0;

    // 1. Món chính vs Món phụ
    const tags = recipe.tags || [];
    const isMain = !tags.includes('canh') && !tags.includes('rau');
    if (isMain) {
      score += 50;
    }
    if (item.notes === 'Món phụ') {
      score -= 20;
    }

    // 2. Món có calories/protein tốt hơn
    const protein = Number(recipe.protein) || 0;
    const calories = Number(recipe.calories || item.calories) || 0;
    score += protein * 2;
    if (calories >= 250 && calories <= 800) {
      score += 15;
    }

    // 3. Món ít bị trùng vs Món bị lặp
    const recipeOccurrences = dayItems.filter(
      (i) => i.recipeId === recipe.id,
    ).length;
    if (recipeOccurrences > 1) {
      score -= 100; // Deduct heavily for duplicate recipes
    }

    // 4. Món phù hợp bữa ăn hơn
    if (recipe.mealType && recipe.mealType.includes(item.mealType)) {
      score += 30;
    }

    return score;
  }

  private pickBestMealItems(
    items: MealPlanItem[],
    limit: number,
    keepIds: Set<string>,
    dayItems: MealPlanItem[],
  ) {
    return items
      .filter((item) => !keepIds.has(item.id))
      .sort((a, b) => {
        if (a.isLocked !== b.isLocked) return a.isLocked ? -1 : 1;

        const scoreA = this.scoreMealPlanItemForKeeping(a, dayItems);
        const scoreB = this.scoreMealPlanItemForKeeping(b, dayItems);
        if (scoreA !== scoreB) {
          return scoreB - scoreA;
        }

        // Keep older item first (Món thêm sau cùng bị loại)
        const timeA = new Date(a.createdAt || 0).getTime();
        const timeB = new Date(b.createdAt || 0).getTime();
        return timeA - timeB;
      })
      .slice(0, Math.max(0, limit));
  }

  private async optimizeMealPlanItemsForPortions(
    planId: string,
    dates: Date[],
    servings: number,
    dailyCalorieTarget?: number,
  ): Promise<{
    optimized: boolean;
    beforeCount: number;
    afterCount: number;
    removedItems: { recipeName: string; mealType: string; dayOfWeek: number }[];
    errorReason: string | null;
  }> {
    const dateStrings = Array.from(
      new Set(dates.map((date) => this.formatDateInput(date))),
    );
    if (dateStrings.length === 0) {
      return {
        optimized: false,
        beforeCount: 0,
        afterCount: 0,
        removedItems: [],
        errorReason: null,
      };
    }

    const allItems = await this.itemRepo.find({
      where: {
        mealPlanId: planId,
        mealDate: In(dateStrings),
      },
      relations: ['recipe'],
    });

    const recipeCount = await this.recipeRepo.count();
    if (recipeCount === 0) {
      return {
        optimized: false,
        beforeCount: allItems.length,
        afterCount: allItems.length,
        removedItems: [],
        errorReason: 'not_enough_recipes',
      };
    }

    const targetDishesPerDay = getMaxRecommendedDishes(servings);
    const idsToRemove: string[] = [];
    const removedItemsDetails: {
      recipeName: string;
      mealType: string;
      dayOfWeek: number;
    }[] = [];
    let beforeCount = allItems.filter((item) => item.recipeId).length;
    let afterCount = beforeCount;
    let errorReason: string | null = null;
    let optimized = false;

    for (const dateStr of dateStrings) {
      const dayItems = allItems.filter(
        (item) =>
          this.formatDateInput(new Date(item.mealDate)) === dateStr &&
          item.recipeId,
      );

      beforeCount = dayItems.length;

      if (dayItems.length <= targetDishesPerDay) {
        afterCount = dayItems.length;
        continue;
      }

      // Check if locked items exceed the threshold
      const lockedItems = dayItems.filter((item) => item.isLocked);
      if (lockedItems.length > targetDishesPerDay) {
        errorReason = `locked_exceeds_limit:${lockedItems.length}:${targetDishesPerDay}`;
        afterCount = dayItems.length;
        break;
      }

      const keepIds = new Set<string>();
      lockedItems.forEach((item) => keepIds.add(item.id));

      for (const mealType of this.MEAL_TYPES) {
        const mealItems = dayItems.filter((item) => item.mealType === mealType);
        const targetForMeal = this.getTargetDishesCount(servings, mealType);
        const lockedInMeal = mealItems.filter((item) => item.isLocked).length;
        const needMore = Math.max(0, targetForMeal - lockedInMeal);

        this.pickBestMealItems(mealItems, needMore, keepIds, dayItems).forEach(
          (item) => keepIds.add(item.id),
        );
      }

      if (keepIds.size < targetDishesPerDay) {
        this.pickBestMealItems(
          dayItems,
          targetDishesPerDay - keepIds.size,
          keepIds,
          dayItems,
        ).forEach((item) => keepIds.add(item.id));
      }

      // Removed nutrition calorie limit check

      const dayToRemove = dayItems.filter(
        (item) => !item.isLocked && !keepIds.has(item.id),
      );
      for (const item of dayToRemove) {
        idsToRemove.push(item.id);
        removedItemsDetails.push({
          recipeName: item.recipe?.name || 'Món ăn không tên',
          mealType: item.mealType,
          dayOfWeek: this.getDayOfWeekIndex(item.mealDate),
        });
      }

      optimized = true;
      afterCount = keepIds.size;
    }

    if (idsToRemove.length > 0 && !errorReason) {
      await this.itemRepo.delete({ id: In(idsToRemove) });
    } else {
      optimized = false;
    }

    return {
      optimized,
      beforeCount,
      afterCount,
      removedItems: removedItemsDetails,
      errorReason,
    };
  }

  private getTargetDishesCount(servings: number, mealType: string): number {
    const s = Math.max(1, Math.floor(Number(servings) || 1));
    if (s <= 1) {
      if (mealType === 'breakfast' || mealType === 'snack') return 1;
      return 2; // lunch, dinner
    }
    if (s <= 2) {
      if (mealType === 'breakfast' || mealType === 'snack') return 2;
      return 3; // lunch, dinner
    }
    if (s <= 4) {
      if (mealType === 'breakfast' || mealType === 'snack') return 2;
      return 5; // lunch, dinner
    }
    if (s <= 6) {
      if (mealType === 'breakfast' || mealType === 'snack') return 3;
      return 6; // lunch, dinner
    }
    // Fallback for > 6 servings
    const max = getMaxRecommendedDishes(s);
    const bf = Math.max(1, Math.round(max * 0.2));
    const ld = Math.max(1, Math.round((max - bf) / 2));
    if (mealType === 'breakfast' || mealType === 'snack') return bf;
    if (mealType === 'lunch') return ld;
    return max - bf - ld; // dinner
  }

  private selectRecipesForSlotWithFallback(
    recommendations: any[],
    targetCount: number,
    context: {
      currentDayRecipeIds: Set<string>;
      currentDayRecipeNames: Set<string>;
      weeklyUsedRecipeIds: Set<string>;
      recentSuggestedRecipes: string[];
      prioritizeNew?: boolean;
      noRepeatIn7Days?: boolean;
    },
    state: { hasUsedDuplicates: boolean },
    dayItemsList: MealPlanItem[] = [],
    dateStr: string = '',
    mealType: string = '',
  ): any[] {
    if (!recommendations || recommendations.length === 0 || targetCount <= 0) {
      return [];
    }

    const candidateRecipes: Recipe[] = [];
    const seenCandidateIds = new Set<string>();
    for (const rec of recommendations) {
      const recipe = rec.recipe;
      if (recipe && recipe.id && !seenCandidateIds.has(recipe.id)) {
        seenCandidateIds.add(recipe.id);
        candidateRecipes.push(recipe);
      }
    }

    const usedRecipeIdsForDay = context.currentDayRecipeIds;
    const duplicateRecipes = candidateRecipes.filter((r) =>
      usedRecipeIdsForDay.has(r.id),
    );
    const duplicateRecipeNames = duplicateRecipes.map((r) => r.name);
    const nonDuplicateCandidates = candidateRecipes.filter(
      (r) => !usedRecipeIdsForDay.has(r.id),
    );

    const selected: Recipe[] = [];
    let reuseReason = '';

    while (selected.length < targetCount && nonDuplicateCandidates.length > 0) {
      const nextRecipe = nonDuplicateCandidates.shift();
      selected.push(nextRecipe);
      usedRecipeIdsForDay.add(nextRecipe.id);
      context.currentDayRecipeNames.add(nextRecipe.name);
    }

    if (selected.length < targetCount) {
      reuseReason = `Không đủ món chưa dùng trong ngày cho bữa ${mealType} (Cần ${targetCount} món, chỉ tìm được ${selected.length} món mới).`;
      state.hasUsedDuplicates = true;

      const getOccurrenceCount = (recipeId: string): number => {
        const countInDayItems = dayItemsList.filter(
          (item) => item.recipeId === recipeId,
        ).length;
        const countInSelected = selected.filter(
          (r) => r.id === recipeId,
        ).length;
        return countInDayItems + countInSelected;
      };

      const reuseCandidates = candidateRecipes.filter((recipe) => {
        const occurrences = getOccurrenceCount(recipe.id);
        return occurrences < 2;
      });

      reuseCandidates.sort((a, b) => {
        const countA = getOccurrenceCount(a.id);
        const countB = getOccurrenceCount(b.id);
        if (countA !== countB) {
          return countA - countB;
        }
        return candidateRecipes.indexOf(a) - candidateRecipes.indexOf(b);
      });

      while (selected.length < targetCount && reuseCandidates.length > 0) {
        const nextRecipe = reuseCandidates.shift();
        selected.push(nextRecipe);
        usedRecipeIdsForDay.add(nextRecipe.id);
        context.currentDayRecipeNames.add(nextRecipe.name);
      }
    }

    this.logger.log(
      `[AI Meal Planner Log] Ngày ${dateStr} - Bữa ${mealType}:
      - Tổng số món khả dụng: ${candidateRecipes.length}
      - Tổng số món đã dùng trong ngày: ${usedRecipeIdsForDay.size}
      - Danh sách món bị loại vì trùng: [${duplicateRecipeNames.join(', ')}]
      - Lý do tái sử dụng: ${reuseReason || 'Không cần tái sử dụng (đủ món mới)'}`,
    );

    return selected;
  }

  private selectRecipesForSlot(
    recommendations: any[],
    targetCount: number,
    usedRecipeIds: Set<string>,
  ): any[] {
    if (!recommendations || recommendations.length === 0) return [];
    if (targetCount <= 1) {
      const found =
        recommendations.find((r) => !usedRecipeIds.has(r.recipe.id)) ||
        recommendations[0];
      if (found?.recipe?.id) {
        usedRecipeIds.add(found.recipe.id);
      }
      return found ? [found.recipe] : [];
    }

    const mains: any[] = [];
    const raws: any[] = []; // vegetables
    const soups: any[] = []; // soup

    for (const rec of recommendations) {
      const recipe = rec.recipe;
      const tags = recipe.tags || [];
      if (tags.includes('canh')) {
        soups.push(recipe);
      } else if (tags.includes('rau')) {
        raws.push(recipe);
      } else {
        mains.push(recipe);
      }
    }

    const selected: any[] = [];

    // Select main dish
    const main = mains.find((r) => !usedRecipeIds.has(r.id)) || mains[0];
    if (main) {
      selected.push(main);
      usedRecipeIds.add(main.id);
    }

    if (targetCount === 2) {
      // Need 1 side dish: either rau or canh
      const side =
        raws.find((r) => !usedRecipeIds.has(r.id)) ||
        soups.find((r) => !usedRecipeIds.has(r.id)) ||
        raws[0] ||
        soups[0];
      if (side) {
        selected.push(side);
        usedRecipeIds.add(side.id);
      }
    } else if (targetCount === 3) {
      // Need 1 rau and 1 canh
      const veg = raws.find((r) => !usedRecipeIds.has(r.id)) || raws[0];
      if (veg) {
        selected.push(veg);
        usedRecipeIds.add(veg.id);
      }
      const soup = soups.find((r) => !usedRecipeIds.has(r.id)) || soups[0];
      if (soup) {
        selected.push(soup);
        usedRecipeIds.add(soup.id);
      }
    }

    // Fallback: if not enough dishes, fill with any unused recommendations
    while (
      selected.length < targetCount &&
      selected.length < recommendations.length
    ) {
      const remaining = recommendations.find(
        (r) => !usedRecipeIds.has(r.recipe.id),
      );
      if (!remaining) {
        const anyRemaining = recommendations.find(
          (r) => !selected.some((s) => s.id === r.recipe.id),
        );
        if (anyRemaining) {
          selected.push(anyRemaining.recipe);
        } else {
          break;
        }
      } else {
        selected.push(remaining.recipe);
        usedRecipeIds.add(remaining.recipe.id);
      }
    }

    return selected;
  }

  async toggleConsume(
    userId: string,
    planId: string,
    itemId: string,
    isConsumed: boolean,
  ) {
    const item = await this.itemRepo.findOne({
      where: { id: itemId, mealPlanId: planId },
      relations: [
        'recipe',
        'recipe.recipeIngredients',
        'recipe.recipeIngredients.ingredient',
      ],
    });
    if (!item) {
      throw new NotFoundException('Không tìm thấy bữa ăn trong thực đơn');
    }

    if (item.isConsumed === isConsumed) {
      return {
        message: 'Trạng thái không thay đổi',
        isConsumed: item.isConsumed,
      };
    }

    const user = await this.userRepo.findOne({
      where: { id: userId },
      relations: ['preferences'],
    });
    if (!user) {
      throw new NotFoundException('Không tìm thấy thông tin người dùng');
    }

    const servings = user.preferences?.servings || 4;
    const recipe = item.recipe;

    item.isConsumed = isConsumed;
    await this.itemRepo.save(item);

    if (
      recipe &&
      recipe.recipeIngredients &&
      recipe.recipeIngredients.length > 0
    ) {
      const recipeServings = recipe.servings || 4;
      const ratio = servings / recipeServings;

      for (const ri of recipe.recipeIngredients) {
        const amountNeeded = Number(ri.quantity) * ratio;

        const invItem = await this.inventoryRepo.findOne({
          where: { userId, ingredientId: ri.ingredientId },
        });

        if (isConsumed) {
          if (invItem) {
            const newQty = Number(invItem.quantity) - amountNeeded;
            if (newQty <= 0) {
              await this.inventoryRepo.remove(invItem);
            } else {
              invItem.quantity = Math.round(newQty * 100) / 100;
              await this.inventoryRepo.save(invItem);
            }
          }
        } else {
          if (invItem) {
            const newQty = Number(invItem.quantity) + amountNeeded;
            invItem.quantity = Math.round(newQty * 100) / 100;
            await this.inventoryRepo.save(invItem);
          } else {
            const newInv = this.inventoryRepo.create({
              userId,
              ingredientId: ri.ingredientId,
              quantity: Math.round(amountNeeded * 100) / 100,
              unit: ri.unit || 'g',
            });
            await this.inventoryRepo.save(newInv);
          }
        }
      }
    }

    return {
      message: isConsumed
        ? 'Đã đánh dấu đã ăn và tự động khấu trừ tủ lạnh'
        : 'Đã hủy đánh dấu đã ăn và khôi phục nguyên liệu tủ lạnh',
      isConsumed: item.isConsumed,
    };
  }
}
