import {
    Entity, PrimaryGeneratedColumn, Column, CreateDateColumn,
    UpdateDateColumn, ManyToOne, OneToMany, JoinColumn,
} from 'typeorm';
import { User } from '../../auth/entities/user.entity';
import { MealPlanItem } from './meal-plan-item.entity';

@Entity('meal_plans')
export class MealPlan {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({ type: 'uuid' })
    userId: string;

    @Column({ type: 'date' })
    weekStart: Date; // Monday

    @Column({ type: 'date' })
    weekEnd: Date;   // Sunday

    @Column({ type: 'int', nullable: true })
    totalCalories: number;

    @Column({ type: 'boolean', default: false })
    isAutoGenerated: boolean;

    @Column({ type: 'varchar', length: 20, default: 'active' })
    status: string; // active | completed | archived

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;

    // --- Relations ---
    @ManyToOne(() => User, (user) => user.mealPlans, { onDelete: 'CASCADE' })
    @JoinColumn({ name: 'userId' })
    user: User;

    @OneToMany(() => MealPlanItem, (item) => item.mealPlan, { cascade: true })
    items: MealPlanItem[];
}
